### ISSUE TITLE
Error while trying to install.

### ISSUE THREAD

**Issue by victorgabr** [tjdevries/gruvbuddy.nvim#1]
```
Error detected while processing /home/victor/.vimrc:
line   64:
E5105: Error while calling lua chunk: ...ctor/.vim/plugged/colorbuddy.vim/lua/colorbuddy/init.lua:9: attempt to
index field 'g' (a nil value)
Press ENTER or type command to continue
```
I got this result by following the installation steps from README.md

**Comment by tjdevries** [comment]
Can you paste me the init.vim to do this? Do you do the `lua ...` stuff after `plug#end(...)`?

**Comment by victorgabr** [comment]
sure

```vimml
call plug#begin('C:\Users\user\AppData\Local\nvim\plugged')

Plug 'ThePrimeagen/vim-be-good', {'do': '.\install.sh'}
" Initialize plugin system

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'gruvbox-community/gruvbox'
Plug 'tjdevries/colorbuddy.vim'
Plug 'tjdevries/gruvbuddy.nvim'
call plug#end()



" And then somewhere in your vimrc, to set the colorscheme
lua require('colorbuddy').colorscheme('gruvbuddy')

```

**Comment by tjdevries** [comment]
What version of neovim do you have?

**Comment by victorgabr** [comment]
NVIM v0.4.3

**Comment by tjdevries** [comment]
Ah, I see. I was using a newer feature only available in HEAD. I just removed it. Can you try updating the plugins and trying again?

**Comment by victorgabr** [comment]
I got the following error:

```
Error detected while processing C:\Users\user\AppData\Local\nvim\init.vim:
line   53:
E5105: Error while calling lua chunk: ...cal\nvim\plugged\colorbuddy.vim\lua\colorbuddy\color.lua:30: atte
mpt to index field 'fn' (a nil value)
Press ENTER or type command to continue
```
But it looks like it put at a "dark background":


![image](https://user-images.githubusercontent.com/6777517/85867308-b5206d00-b796-11ea-9933-8d209361b874.png)

**Comment by tjdevries** [comment]
OK, want to try again for me now? I just pushed some updates after downloading 0.4.3 :) I haven't used that release in a long time since I usually build from source.

Should contain the updates required to get this to work for you. Thanks for being patient!

**Comment by victorgabr** [comment]
Sure, and now I got a new error message and new colors:

```

Error detected while processing C:\Users\user\AppData\Local\nvim\init.vim:
line   53:
E5105: Error while calling lua chunk: ...m\plugged\colorbuddy.vim\lua\colorbuddy\plugins\init.lua:113: att
empt to concatenate a nil value
Press ENTER or type command to continue
```

![image](https://user-images.githubusercontent.com/6777517/85870220-c7040f00-b79a-11ea-86a5-406949731e11.png)

**Comment by tjdevries** [comment]
Oh! Windows! Ok :) I can fix.

**Comment by victorgabr** [comment]
I can test on Linux later. 
But so far, at least the first error I got was the same in both Windows and Linux.

**Comment by tjdevries** [comment]
Yup, the first errors were my fault -- I was using functions only available in neovim HEAD. This one is because I tried to split a path with `/` instead of path separators... :cry:

**Comment by tjdevries** [comment]
OK, I have attempted windows support :) let me know if that fixed it.

**Comment by victorgabr** [comment]
Fixed. 
No error messages.
![image](https://user-images.githubusercontent.com/6777517/85872622-ff591c80-b79d-11ea-964c-a1ca87daf1c2.png)
I am going to close this issue.

**Comment by tjdevries** [comment]
Awesome, thanks for helping me figure that stuff out :)
