### ISSUE TITLE
Keep getting this error when trying to use the color scheme 

### ISSUE THREAD

**Issue by jacobduncan00** [tjdevries/gruvbuddy.nvim#2]
[https://imgur.com/nBMC4iK](Screenshot)

I have neovim installed. I am using the commands listed in your installation. I have plugged your two repository with vim plug and installed them but this is the error I keep getting. 

Do I need Lua installed?

**Comment by jacobduncan00** [comment]
Installed lua and still having the issue

**Comment by tjdevries** [comment]
What version of neovim do you have?

Can you paste me the results of `:version`?

**Comment by jacobduncan00** [comment]
:version output

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORT
IFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-pr
ototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fsta
ck-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVI
M_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3
/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/n
eovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/
Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sd
k/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim
-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info

**Comment by tjdevries** [comment]
Huh, that's an old version of LuaJit -- but I don't think that should be the problem.

Can you paste me the init.vim you're using (or send me a link if that's easier)?

**Comment by jacobduncan00** [comment]
`" tabs
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab
set backspace=indent,eol,start
set mouse=a
set noswapfile

set number
set numberwidth=5

" display extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

" terminal colors
" set t_Co=256
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" vim airline
set laststatus=2
" let g:airline_theme='one'

" set background=dark


" ale highlight
highlight ALEwarning ctermbg=DarkMagenta

" GO highlighting
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:SnazzyTransparent = 1
" automatically start NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>

" close a tab if only remaining window is NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

set tags=tags
autocmd BufWritePost *.py silent! !ctags -R --python-kinds=-i --languages=python 2&gt; /dev/null &amp;

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'mattn/emmet-vim'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'kien/ctrlp.vim'
Plug 'bling/vim-airline'
Plug 'hdima/python-syntax'
Plug 'tpope/vim-markdown'
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'joshdick/onedark.vim'
Plug 'connorholyday/vim-snazzy'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tjdevries/colorbuddy.vim'
Plug 'tjdevries/gruvbuddy.nvim'

call plug#end()

syntax enable

lua require('colorbuddy').colorscheme('gruvbuddy')

inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>":
    \ <SID>check_back_space() ? "\<TAB>":
    \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1] =~# '\s'
end-function
`

**Comment by jacobduncan00** [comment]
I'm stupid and was using vim instead of nvim OmegaLUL
